### PR TITLE
use Vec::drain in channel read

### PR DESCRIPTION
**Pull request by npry**
was watching the vod and thought there had to be a better way to handle buffering data reads from `Channel` than maintaining a `data_start` bookkeeping field. `Vec::drain` seems to be pretty much what you'd want--it just removes the elements from the specified range and returns them in an iterator.

the way i've used it here is less efficient than using `copy_from_slice` because it doesn't use the `copy_nonoverlapping` intrinsic, but you could recover that performance if you wanted by instead doing a `copy_from_slice` the way you had it, then `drain`ing the elements again (this is zero-allocation per [Vec source](https://doc.rust-lang.org/src/alloc/vec.rs.html#1089-1130)).

### CODE REVIEW

**Comment by jonhoo** [comment]
Hey! Thanks for this. I know of `drain` with a range, but intentionally did not use it here for a slightly different reason. Specifically, if you look at the [`impl Drop for Drain`](https://doc.rust-lang.org/src/alloc/vec.rs.html#2485-2503), you'll see that after the `drain` completes, it *copies* all elements after `end` to the beginning of the `Vec`. This is necessary to ensure that the `Vec` remains valid (specifically, that `[0]` is at the beginning of its allocation). In our case, this would translate to copying all bytes *not* read every time `read` is called. The current code never has to do this extra copying, at the cost of keeping a little bit extra memory around (and the extra bookkeeping).

Arguably I should have mentioned this reasoning in the video, but it escaped my mind in the heat of the moment :p This is a trade-off between performance and readability, and arguably what I did is premature optimization. Copying all the data every time just seemed pretty expensive at the time.. I think I'll leave the code as it is for the time being, but perhaps it'd be useful to include a comment there explaining why we do things this way. Perhaps you'd want to submit a PR adding a comment based on your understanding of it after reading this? :)

**Comment by npry** [comment]
ah! okay, that makes total sense. perhaps something like a growable ringbuffer would be a nice structure here, then? maybe i'll take a look at writing a simple crate for that. and sure, i'd be happy to leave a comment.

**Comment by birkenfeld** [comment]
Wouldn't the std `VecDeque` be exactly that? Its drain should just move the front end of the queue.

**Comment by jonhoo** [comment]
Oooh, yeah, that's a great idea! I'd happily accept a PR moving it to `VecDeque`.

**Pull request closed without merging**
